### ISSUE TITLE
when simulating NU observations, std of observation can lead to large errors in test score.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#17]
When simulating neuronunit observations, std of observation can lead to large errors in test score, as scores are computed by (mean1-mean0)/std. If std is x<1.0 then mean1-mean0 can inappropriately inflate, therefore there should be checks and warnings. This may be a problem with some types of experimental NU observations too.

**Comment by rgerkin** [comment]
What is wrong with std < 1.0?  If std is really that small, and mean1-mean0 is large, then the score should be high.  

Is this a problem specifically with simulated observations, where the the simulations are deterministic, so std ~ 0?  For deterministic observations (i.e. observations from deterministic simulations) I would just not use Z-scores at all since std would be meaningless.

**Comment by russelljjarvis** [comment]
The answer you propose is a good idea, but the code seems to work with high standard deviation. I will try to phase in the approach you describe here in time.

**Comment by russelljjarvis** [comment]
I think this will occur for models whose V_m is a thousandfold magnitude too small (correct_vm*1/1000.0)

**Comment by rgerkin** [comment]
Let `m` equal the model vm mean, `o` equal the observed vm mean, and `s` equal the observed vm standard deviation.  So the Z-score is `(m-o)/s`.  

Imagine `m` changing by 10% (lower, for example, to 90% of it's previous value) as the parameter space is explored.  This would produce a change in the Z-score to `(m*0.9-o)/s`.  So the change in the Z-score would be `(m-o)/s` - `(m*0.9-o)/s` = `m*0.1/s`.  The optimizer requires this change in the Z-score to be large enough to follow its gradient.  But this change will be very small whenever `m` is small or `s` is large, which I think is what you are seeing.  

If `m` changes by an additive factor (e.g. from a change in the `v_r` parameter) then the initial size of `m` probably doesn't matter, but for some other parameters, at some locations in parameter space, the effect on `m` could be multiplicative, e.g. a change of 10% from the previous value.  

Overall, it seems like ensuring that the gradient is of an appropriate magnitude is pretty important.  Maybe it is possible to always shape the normalized score to be very steep when it is far from optimal, and only become shallow when it is starting to get near the observed value.  As I currently have the normalized score implemented (or however you are implementing it right now to produce the return value of the objective function), it seems that it may still remain too shallow, too far away from the optimum.  

Doing this probably means that the range of the normalized score can't be 0-1 (at least not the version of the normalized score that is used for optimization).  Because "bad" is close to 0, but "really, really bad" can only be closer to 0, and that isn't enough of a gap.  A simple transformation would be log(normalized_score), so then the range is from -Inf to 0.  It would never actually be -Inf, because the original normalizer should never give 0 anyway, but it could be really, really negative, so that a bad model is still considered a big improvement over a really, really bad and ridiculous model.
