### ISSUE TITLE
Populate sciunit Score Matrices with optimizer outputs

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#22]
The entry point for that is here:
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/optimisation/optimization_management.py#L135-L142
ga_out contains everything, from tests, scores, genes, logbooks, dtc.tests etc.

**Comment by russelljjarvis** [comment]
https://github.com/russelljjarvis/neuronunit/blob/a27e984e93a89460dc59d08063ae3b26aa50a53a/neuronunit/optimisation/optimization_management.py#L321

**Comment by rgerkin** [comment]
@russelljjarvis Could you point me to a notebook (or create one) that I can run, in which this line will be reached?  Then I could explore the content of `ga_out` and figure out how to map it to the ScoreMatrix.

**Comment by russelljjarvis** [comment]
Chapter 9 has a lot of lower level control of the OptMan class.
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/examples/chapter9.ipynb
chapter6 cell 3 would also need to execute as a test.
https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/examples/chapter6.ipynb

In terms of code that would need to pass without breaking (not quite a unit test, but a low threshold test of code brittleness). The code below would need to pass.
```python
from neuronunit.examples import elephant_data_tests
a = elephant_data_tests.testHighLevelOptimisation()
a.setUp()
out = a.test_data_driven_ae()
out = a.test_data_driven_rt_ae()
```
You can call it in a notebook. It lives [here](https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/examples/use_edt.py).

**Comment by russelljjarvis** [comment]
This seems to be working, but scores matrices not storable inside data transport containers as not pickable.

**Comment by rgerkin** [comment]
Do you know what is not picklable about them?  As you may recall there is an [`unpicklable` attribute](https://github.com/scidash/sciunit/blob/3b7cd62ee8a8971a43560b1c7344e179c7b53712/sciunit/base.py#L122) on every base SciUnit object, and if that is set appropriately it should be possible to pickle and unpickle a ScoreMatrix or any of its attributes.  Of course, there is the possibility for data loss if one of the unpicklable things is unique and not settable again after unpickling.

**Comment by russelljjarvis** [comment]
I think that it is in fact pickleable. I can populate the matrix. But I can't make the tests inside the matrix, update their scores. Here is an example:
```python
for t in SM: print(t)
RheobaseTest
InputResistanceTest
TimeConstantTest
CapacitanceTest
RestingPotentialTest
InjectedCurrentAPWidthTest
InjectedCurrentAPAmplitudeTest
InjectedCurrentAPThresholdTest
(Pdb) for t in SM: t.judge(model)
Ratio = 0.47
Z = 0.34
Z = -0.40
Z = -0.55
Z = -0.14
{'mean': array(-65.6396559) * mV, 'std': array(65.6396559) * mV} {'mean': array(-75.) * mV, 'std': array(0.) * mV}
Z = -0.14
{'amplitude': array(0.086689) * pA, 'delay': array(100.) * ms, 'duration': array(1000.) * ms}
{'amplitude': array(0.086689) * pA, 'delay': array(100.) * ms, 'duration': array(1000.) * ms}
Z = -0.28
Z = -0.11
Z = -0.62
(Pdb) dir()
['SM', 'dtc', 'error', 'k', 'key', 'model', 'pdb', 'score', 'self', 't', 'tests']
(Pdb) SM
                                   RheobaseTest  ...                 InjectedCurrentAPThresholdTest
  <class 'sciunit.scores.incomplete.NoneScore'>  ...  <class 'sciunit.scores.incomplete.NoneScore'>

[1 rows x 8 columns]
(Pdb) SM[0]
*** TypeError: Expected test; model; test,model; or model,test
(Pdb) SM[1]
*** TypeError: Expected test; model; test,model; or model,test
(Pdb) SM.values()
*** TypeError: 'numpy.ndarray' object is not callable
(Pdb) SM.values
array([[<class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>,
        <class 'sciunit.scores.incomplete.NoneScore'>]], dtype=object)
```

**Comment by rgerkin** [comment]
The error `TypeError: Expected test; model; test,model; or model,test` is telling you that you need to access them by object (or name of object) rather than by index.  So the ScoresMatrix contains scores in an 1x8 shape, but you cannot access them with `SM[0]`, `SM[1]`, etc.  But you can access them by `SM[tests[0]]`, `SM[tests[1]]`, etc., where `tests[0]` is a particular test instance (e.g. some `RheobaseTest`).  You can also access by tests name, so if the RheobaseTest has name 'rheobase_test`, then you can also just do `SM['rheobase_test']`.  

All of that will just give you a slice of the ScoreMatrix, though, which will be a ScoreArray indexed by model.  This is analogous to a 2D numpy array being given one index and returning a 1D numpy array, i.e. expected behavior.  So you can access the score itself by then using the model as an index just as you used above, i.e. `models[0]`, the model instance itself, or the name of the model as a string.

So that is how you extract the scores.  If you need to extract the models or tests themselves, you can access `SM.models` or `SM.tests`, or if you have the original tests and models in memory from earlier in the script (as you do here), you can just use those, since they will be the same.

**Comment by rgerkin** [comment]
@russelljjarvis Can you set the github-actions bot to not close issues so quickly?  One week of inactivity seems pretty short.  

Also, let please close this issue if it is indeed resolved, or leave it open and comment if it is not.
