### ISSUE TITLE
catch instances when sciunit-Ratio scores fail, in order to create coherant sciunit scores and error gradients.

### ISSUE THREAD

**Issue by russelljjarvis** [russelljjarvis/NeuronunitOpt#26]
catch instances when sciunit-Ratio scores fail, by putting a debugger break point in the ```except:``` clause at this [location](https://github.com/russelljjarvis/neuronunit/blob/master/neuronunit/optimisation/optimization_management.py#L1901-L1908).

The methods `bridge_judge`, and `bridge_passive` are both sites where NU scores get messy with a mixture of ZScore, and RatioScore, and observations with observation['std']=0*units.

It might be worth creating a special score that given any category of observation and prediction, it can always generate an error gradient.

**Comment by rgerkin** [comment]
@russelljjarvis I'm having trouble finding the correct line (your link is to master instead of the HEAD commit when you wrote it, and so that file has changed several times in the last few days).  As there will usually be a few day lag between you posting the issues and me looking (or vice versa), let's both make a habit of linking to specific commits when line numbers are involved.

**Comment by russelljjarvis** [comment]
Although file lines have changed during the discussion, the method signatures have remained stable.
In the file optimization_management. Search for functions ```bridge_judge``` and ```bridge_passive```. These circumvent calling sciunit judge, by instead calling ```generate_prediction```, or ```extract_features``` and ```compute_score``` as appropriate. What I describe is a big hack, that could probably easily be replaced with an elegant solution, given your knowledge of the current state of sciunit scores.
